version: '3'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
  # app:
  #   build: ./app
  #   command: python3 -m app
  #   restart: on-failure
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db