version: '3'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      "db.env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

  app:
    build: ./app
    env_file:
      "app.env"
    command: python3 -m app
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db