FROM python:3.10-slim

WORKDIR /env_project

RUN apt-get update 
RUN apt-get install libgl1 libglib2.0-0 ffmpeg libsm6 libxext6  -y

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . ./app